#!/bin/sh /etc/rc.common

VERSION="1.0.0"
START=99
STOP=01
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /etc/5g/init_crontab.sh
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "lede"
}